# Preparando los datos para el modelo de machine learning

In [2]:
import numpy as np
import pandas as pd

pd.options.display.max_columns = 50

Se cargan los dataset necesarios

In [3]:
data2 = pd.read_csv('archive\indicadores_EVN.csv')
data2

,country,year,"Life expectancy at birth, female (years)","Life expectancy at birth, total (years)","Life expectancy at birth, male (years)",Urban population (% of total population),Rural population (% of total population),Population growth (annual %),"Inflation, consumer prices (annual %)",Gini index,"Inflation, GDP deflator (annual %)",GDP (current US$),GDP per capita (current US$),GDP per capita growth (annual %),GNI (current US$),Current health expenditure (% of GDP),"Hospital beds (per 1,000 people)",Domestic private health expenditure per capita (current US$),Current health expenditure per capita (current US$),"Mortality caused by road traffic injury (per 100,000 population)",People using at least basic sanitation services (% of population),People using safely managed drinking water services (% of population),"Literacy rate, adult total (% of people ages 15 and above)",Control of Corruption: Estimate,Military expenditure (% of GDP),General government final consumption expenditure (current US$),Access to electricity (% of population),Food exports (% of merchandise exports),Food production index (2014-2016 = 100),Households and NPISHs final consumption expenditure (% of GDP),"School enrollment, tertiary (gross), gender parity index (GPI)","School enrollment, tertiary (% gross)",Internet Users(%)
0,EGY,2022,NaN,NaN,NaN,42.967,57.033,1.569074,13.895661,NaN,10.425789,4.767477e+11,4295.407496,4.928456,4.609845e+11,NaN,NaN,NaN,NaN,NaN,97.528750,NaN,NaN,NaN,1.061810,3.465046e+10,NaN,13.607104,NaN,82.522155,NaN,NaN,NaN
1,EGY,2021,72.608,70.221,67.935,42.862,57.138,1.658384,5.214049,NaN,4.847156,4.246718e+11,3886.722498,1.591816,4.122726e+11,NaN,NaN,NaN,NaN,NaN,97.524650,NaN,73.089996,-0.684838,1.122009,3.209688e+10,100.0,14.321835,102.75,86.005013,NaN,NaN,NaN
2,EGY,2020,73.390,70.990,68.667,42.783,57.217,1.733130,5.044933,NaN,6.176934,3.838178e+11,3571.556907,1.770969,3.724638e+11,4.364980,NaN,101.035651,150.906555,NaN,97.521561,NaN,NaN,-0.789792,1.122476,2.893949e+10,100.0,18.070859,103.76,83.645938,NaN,NaN,71.914200
3,EGY,2019,73.711,71.358,69.049,42.730,57.270,1.794002,9.152800,31.9,13.618096,3.186788e+11,3017.258336,3.675371,3.076692e+11,4.836193,NaN,102.819814,145.310760,10.1,97.200558,NaN,NaN,-0.634925,1.180972,2.321754e+10,100.0,16.573575,100.61,80.496783,NaN,NaN,57.282867
4,EGY,2018,73.927,71.367,68.875,42.704,57.296,1.898931,14.401466,NaN,21.174821,2.625886e+11,2531.200079,3.349815,2.563090e+11,4.993793,NaN,85.210025,120.223259,10.3,96.881001,NaN,NaN,-0.492104,1.249966,2.085537e+10,100.0,15.793587,96.32,83.290472,1.04445,38.904949,46.924335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2074,CHN,1964,54.337,52.156,50.157,18.299,81.701,2.320683,NaN,NaN,-0.362038,5.970813e+10,85.498246,15.468995,5.970813e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.573671e+09,NaN,NaN,13.05,60.521124,NaN,NaN,NaN
2075,CHN,1963,53.608,51.408,49.407,17.757,82.243,2.457647,NaN,NaN,-2.621611,5.070662e+10,74.313375,7.622254,5.070662e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.863108e+09,NaN,NaN,12.32,67.627974,NaN,NaN,NaN
2076,CHN,1962,53.040,50.818,48.813,17.226,82.774,0.820456,NaN,NaN,-0.114965,4.720919e+10,70.909155,-6.351505,4.720919e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.990304e+09,NaN,NaN,11.77,72.164860,NaN,NaN,NaN
2077,CHN,1961,42.148,40.468,38.982,16.708,83.292,-1.015528,NaN,NaN,15.253994,5.005669e+10,75.805564,-26.527644,5.005669e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.157317e+09,NaN,NaN,11.10,66.274446,NaN,NaN,NaN
2078,CHN,1960,34.615,33.275,32.110,16.203,83.797,NaN,NaN,NaN,NaN,5.971625e+10,89.520218,NaN,5.971625e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.429205e+09,NaN,NaN,NaN,50.452350,NaN,NaN,NaN

Se conservan solo las columnas necesarias para el modelo

In [4]:
data2.columns

Index(['country', 'year', 'Life expectancy at birth, female (years)',
       'Life expectancy at birth, total (years)',
       'Life expectancy at birth, male (years)',
       'Urban population (% of total population)',
       'Rural population (% of total population)',
       'Population growth (annual %)', 'Inflation, consumer prices (annual %)',
       'Gini index', 'Inflation, GDP deflator (annual %)', 'GDP (current US$)',
       'GDP per capita (current US$)', 'GDP per capita growth (annual %)',
       'GNI (current US$)', 'Current health expenditure (% of GDP)',
       'Hospital beds (per 1,000 people)',
       'Domestic private health expenditure per capita (current US$)',
       'Current health expenditure per capita (current US$)',
       'Mortality caused by road traffic injury (per 100,000 population)',
       'People using at least basic sanitation services (% of population)',
       'People using safely managed drinking water services (% of population)',
       'Literacy rate, adult total (% of people ages 15 and above)',
       'Control of Corruption: Estimate', 'Military expenditure (% of GDP)',
       'General government final consumption expenditure (current US$)',
       'Access to electricity (% of population)',
       'Food exports (% of merchandise exports)',
       'Food production index (2014-2016 = 100)',
       'Households and NPISHs final consumption expenditure (% of GDP)',
       'School enrollment, tertiary (gross), gender parity index (GPI)',
       'School enrollment, tertiary (% gross)'],
      dtype='object')

In [3]:
data2 = data2.drop(columns=['Urban population (% of total population)','Rural population (% of total population)',
                            'Hospital beds (per 1,000 people)',
                            'Domestic private health expenditure per capita (current US$)','Domestic private health expenditure per capita (current US$)',
                            'Current health expenditure per capita (current US$)',
                            'Mortality caused by road traffic injury (per 100,000 population)',
                            'Literacy rate, adult total (% of people ages 15 and above)',
                            'People using at least basic sanitation services (% of population)',
                            'People using safely managed drinking water services (% of population)',
                            'Control of Corruption: Estimate', 'Military expenditure (% of GDP)',
                            'General government final consumption expenditure (current US$)',
                            'Access to electricity (% of population)',
                            'Food exports (% of merchandise exports)',
                            'Food production index (2014-2016 = 100)',
                            'Households and NPISHs final consumption expenditure (% of GDP)',])

In [4]:
print(data2.columns)
data2

Index(['country', 'year', 'Life expectancy at birth, female (years)',
       'Life expectancy at birth, total (years)',
       'Life expectancy at birth, male (years)',
       'Population growth (annual %)', 'Inflation, consumer prices (annual %)',
       'Gini index', 'Inflation, GDP deflator (annual %)', 'GDP (current US$)',
       'GDP per capita (current US$)', 'GDP per capita growth (annual %)',
       'GNI (current US$)', 'Current health expenditure (% of GDP)',
       'School enrollment, tertiary (gross), gender parity index (GPI)',
       'School enrollment, tertiary (% gross)', 'Internet Users(%)'],
      dtype='object')

,country,year,"Life expectancy at birth, female (years)","Life expectancy at birth, total (years)","Life expectancy at birth, male (years)",Population growth (annual %),"Inflation, consumer prices (annual %)",Gini index,"Inflation, GDP deflator (annual %)",GDP (current US$),GDP per capita (current US$),GDP per capita growth (annual %),GNI (current US$),Current health expenditure (% of GDP),"School enrollment, tertiary (gross), gender parity index (GPI)","School enrollment, tertiary (% gross)",Internet Users(%)
0,EGY,2022,NaN,NaN,NaN,1.569074,13.895661,NaN,10.425789,4.767477e+11,4295.407496,4.928456,4.609845e+11,NaN,NaN,NaN,NaN
1,EGY,2021,72.608,70.221,67.935,1.658384,5.214049,NaN,4.847156,4.246718e+11,3886.722498,1.591816,4.122726e+11,NaN,NaN,NaN,NaN
2,EGY,2020,73.390,70.990,68.667,1.733130,5.044933,NaN,6.176934,3.838178e+11,3571.556907,1.770969,3.724638e+11,4.364980,NaN,NaN,71.914200
3,EGY,2019,73.711,71.358,69.049,1.794002,9.152800,31.9,13.618096,3.186788e+11,3017.258336,3.675371,3.076692e+11,4.836193,NaN,NaN,57.282867
4,EGY,2018,73.927,71.367,68.875,1.898931,14.401466,NaN,21.174821,2.625886e+11,2531.200079,3.349815,2.563090e+11,4.993793,1.04445,38.904949,46.924335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2074,CHN,1964,54.337,52.156,50.157,2.320683,NaN,NaN,-0.362038,5.970813e+10,85.498246,15.468995,5.970813e+10,NaN,NaN,NaN,NaN
2075,CHN,1963,53.608,51.408,49.407,2.457647,NaN,NaN,-2.621611,5.070662e+10,74.313375,7.622254,5.070662e+10,NaN,NaN,NaN,NaN
2076,CHN,1962,53.040,50.818,48.813,0.820456,NaN,NaN,-0.114965,4.720919e+10,70.909155,-6.351505,4.720919e+10,NaN,NaN,NaN,NaN
2077,CHN,1961,42.148,40.468,38.982,-1.015528,NaN,NaN,15.253994,5.005669e+10,75.805564,-26.527644,5.005669e+10,NaN,NaN,NaN,NaN
2078,CHN,1960,34.615,33.275,32.110,NaN,NaN,NaN,NaN,5.971625e+10,89.520218,NaN,5.971625e+10,NaN,NaN,NaN,NaN

# Recolectando los datos para el modelo (anios 2012-2022)

In [6]:
data2.columns

Index(['country', 'year', 'Life expectancy at birth, female (years)',
       'Life expectancy at birth, total (years)',
       'Life expectancy at birth, male (years)',
       'Population growth (annual %)', 'Inflation, consumer prices (annual %)',
       'Gini index', 'Inflation, GDP deflator (annual %)', 'GNI (current US$)',
       'Current health expenditure (% of GDP)',
       'School enrollment, tertiary (gross), gender parity index (GPI)',
       'School enrollment, tertiary (% gross)', 'Internet Users(%)'],
      dtype='object')

In [13]:
data2['Inflation, consumer prices (annual %)'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2079 entries, 0 to 2078
Series name: Inflation, consumer prices (annual %)
Non-Null Count  Dtype
--------------  -----
1868 non-null   float64
dtypes: float64(1)
memory usage: 16.4 KB

In [4]:
yrs = [i for i in range(2012,2023)]


training_set = data2[data2['year'].isin(yrs)][['year','country','Life expectancy at birth, total (years)','Population growth (annual %)',
                                'School enrollment, tertiary (% gross)','Internet Users(%)','GDP per capita (current US$)',
                                'Inflation, consumer prices (annual %)']]

training_set

,year,country,"Life expectancy at birth, total (years)",Population growth (annual %),"School enrollment, tertiary (% gross)",Internet Users(%),GDP per capita (current US$),"Inflation, consumer prices (annual %)"
0,2022,EGY,NaN,1.569074,NaN,NaN,4295.407496,13.895661
1,2021,EGY,70.221,1.658384,NaN,NaN,3886.722498,5.214049
2,2020,EGY,70.990,1.733130,NaN,71.914200,3571.556907,5.044933
3,2019,EGY,71.358,1.794002,NaN,57.282867,3017.258336,9.152800
4,2018,EGY,71.367,1.898931,38.904949,46.924335,2531.200079,14.401466
...,...,...,...,...,...,...,...,...
2022,2016,CHN,77.218,0.573051,48.019020,53.200001,8094.390375,2.000002
2023,2015,CHN,76.977,0.581456,46.040428,50.299999,8016.446016,1.437024
2024,2014,CHN,76.717,0.630326,42.430729,47.900002,7636.074223,1.921642
2025,2013,CHN,76.452,0.666073,32.433670,45.799999,7020.385682,2.621050
2026,2012,CHN,76.192,0.678345,28.725670,42.300117,6300.582352,2.619524

In [22]:
training_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 363 entries, 0 to 2026
Data columns (total 8 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   year                                     363 non-null    int64
 1   country                                  363 non-null    object
 2   Life expectancy at birth, total (years)  330 non-null    float64
 3   Population growth (annual %)             363 non-null    float64
 4   School enrollment, tertiary (% gross)    252 non-null    float64
 5   Internet Users(%)                        297 non-null    float64
 6   GDP per capita (current US$)             355 non-null    float64
 7   Inflation, consumer prices (annual %)    345 non-null    float64
dtypes: float64(6), int64(1), object(1)
memory usage: 25.5+ KB

In [21]:
training_set['country'] = training_set['country'].astype(str)

In [25]:
len(training_set.dropna())

240

se guardan los datos excluyendo a los nulos

In [26]:
training_set.dropna().to_csv('archive/data4model.csv', index=False)